apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo-{{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo-{{ .Release.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Object 
      object:
        describedObject:
          kind: Service
          name: podinfo
        metric:
          name: http_requests_per_minute
        target:
          type: Value
          value: "{{ .Values.hpa.httpRequestsRateValue }}"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilisationWindow }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.stabilisationWindow }} 