apiVersion: v1
kind: Service
metadata:
  name: podinfo-{{ .Release.Name }}-service
  namespace: {{ .Release.Namespace}}
  labels:
    app: podinfo-{{ .Release.Name }}
spec:
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: podinfo-{{ .Release.Name }}