apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-{{ .Release.Name }}
  labels:
    app: podinfo-{{ .Release.Name }}
spec:
  endpoints: 
    - port: http
      interval: 30s
      targetPort: {{.Values.service.port}}
  selector: 
    matchLabels: 
      app: podinfo-{{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
      